apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bizleal-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eersoy84/kubernetes.git
    targetRevision: HEAD
    path: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bizleal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true