apiVersion: v1
kind: ConfigMap
metadata:
  name: bizleal-api-config
  namespace: bizleal
data:
  PORT: "5000"
  MYSQL_DATABASE: "bizleal"
  USER: "root"
  REDIS_PORT: "6379"
  MASTER_DB: mysql-cluster #service name for mysql master database
  READ_ONLY_DB:  mysql-cluster #service name for mysql replica databases
  REDIS_HOST: redis-service
  WRITE_PORT: "6446"
  READ_PORT: "6447"
  

# MYSQL_CLUSTER_SERVICE_PORT_MYSQL_RO