apiVersion: v1
kind: Secret
metadata:
  name: bizleal-api-sercret
  namespace: bizleal
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlpYbDFjR1Z5YzI5NU9rRnJjQzR5TURBeU1BPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson