apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-production
  namespace: bizleal
spec:
  secretName: ssl-cert-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: bizleal.net
  dnsNames:
  - bizleal.net
  - api.bizleal.net
  - pma.bizleal.net